# Generated by Django 6.0.3 on 2026-04-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneTelephonique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('type_abonnement', models.CharField(blank=True, max_length=50, null=True)),
                ('num_contrat', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_abonnement', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligne Téléphonique',
                'db_table': 'lignes_telephoniques',
            },
        ),
    ]
