# Generated by Django 6.0.3 on 2026-03-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prefixes_tel', models.JSONField(default=list)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centre de Distribution',
                'verbose_name_plural': 'Centres de Distribution',
                'db_table': 'centres_distribution',
            },
        ),
        migrations.CreateModel(
            name='ParametresCentre',
            fields=[
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parametres', serialize=False, to='centres.centredistribution')),
                ('attribution_auto_active', models.BooleanField(default=True)),
                ('sla_heures_normale', models.IntegerField(default=48)),
                ('sla_heures_haute', models.IntegerField(default=24)),
                ('sla_heures_critique', models.IntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Centre',
                'db_table': 'parametres_centre',
            },
        ),
    ]
