# Generated by Django 6.0.3 on 2026-03-29 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_escalade', models.CharField(choices=[('technique', 'Technique'), ('annexe', 'Annexe')], max_length=10)),
                ('motif', models.TextField()),
                ('resume_ia', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pris_en_charge_a', models.DateTimeField(blank=True, null=True)),
                ('resolu_a', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escalade',
                'db_table': 'escalades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_mime', models.CharField(max_length=100)),
                ('taille_octets', models.IntegerField()),
                ('contenu', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'db_table': 'pieces_jointes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(blank=True, max_length=30, unique=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('escalade_technique', 'Escaladé - Technique'), ('escalade_annexe', 'Escaladé - Annexe'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('rejete', 'Rejeté')], default='ouvert', max_length=25)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attribution_auto', models.BooleanField(default=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('satisfaction_client', models.SmallIntegerField(blank=True, null=True)),
                ('commentaire_satisfaction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pris_en_charge_a', models.DateTimeField(blank=True, null=True)),
                ('resolu_a', models.DateTimeField(blank=True, null=True)),
                ('ferme_a', models.DateTimeField(blank=True, null=True)),
                ('echeance_sla', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite_defaut', models.SmallIntegerField(default=2)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de Service',
                'verbose_name_plural': 'Types de Service',
                'db_table': 'types_service',
            },
        ),
    ]
