# Generated by Django 6.0.3 on 2026-03-29 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escalade',
            name='agent_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalades_cible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalade',
            name='agent_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escalades_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent_annexe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_annexe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_technique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='centres.centredistribution'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='escalade',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalades', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='tickets.typeservice'),
        ),
    ]
