# Generated by Django 6.0.3 on 2026-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_email', models.EmailField(max_length=254)),
                ('type_email', models.CharField(choices=[('ticket_ouvert', 'Ticket Ouvert'), ('ticket_attribue', 'Ticket Attribué'), ('nouveau_message', 'Nouveau Message'), ('statut_change', 'Statut Changé'), ('escalade', 'Escalade'), ('ticket_resolu', 'Ticket Résolu'), ('rappel_sla', 'Rappel SLA')], max_length=20)),
                ('sujet', models.CharField(max_length=255)),
                ('corps_html', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=15)),
                ('tentatives', models.SmallIntegerField(default=0)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('envoye_a', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'db_table': 'emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
