# Generated by Django 6.0.3 on 2026-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur_type', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('agent_technique', 'Agent Technique'), ('agent_annexe', 'Agent Annexe'), ('systeme', 'Système')], max_length=20)),
                ('contenu', models.TextField()),
                ('lu_par_client', models.BooleanField(default=False)),
                ('lu_par_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifie_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
